sda

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -6,14 +6,24 @@
 
 
 
-if [ $# -lt 4 ]; then
+
+
+
+
+if [ $# -ne 4 ]; then
     echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
     exit 1
-else
-    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~"
-    if [ $? -eq 0 ]; then
-        echo "File transferred successfully."
-    else
-        echo "File transfer failed."
-    fi
 fi
+
+FILE_PATH=$1
+SERVER_IP=$2
+USERNAME=$3
+SSH_KEY=$4
+
+scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP:~"
+if [ $? -eq 0 ]; then
+    echo "File transferred successfully."
+else
+    echo "File transfer failed."
+fi
+
