web server load balance redo master

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -5,65 +5,65 @@
 # uncomment to see the script run in action
 #set -x
 
-# echo -e "Updating and doing some minor checks...\n"
+echo -e "Updating and doing some minor checks...\n"
 
-# function install() {
-# 	command -v "$1" &> /dev/null
+function install() {
+	command -v "$1" &> /dev/null
 
-# 	#shellcheck disable=SC2181
-# 	if [ $? -ne 0 ]; then
-# 		echo -e "	Installing: $1$\n"
-# 		sudo apt-get update -y -qq && \
-# 			sudo apt-get install -y "$1" -qq
-# 		echo -e "\n"
-# 	else
-# 		echo -e "	${1} is already installed.\n"
-# 	fi
-# }
+	#shellcheck disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "	Installing: $1$\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "	${1} is already installed.\n"
+	fi
+}
 
-# # Install nginx on web-01 server
-#  install nginx #install nginx
+# Install nginx on web-01 server
+install nginx #install nginx
 
-# echo -e "\nSetting up some minor stuff.\n"
+echo -e "\nSetting up some minor stuff.\n"
 
-# # allowing nginx on firewall
-# sudo ufw allow 'Nginx HTTP'
+# allowing nginx on firewall
+#sudo ufw allow 'Nginx HTTP'
 
-# # Give the user ownership to website files for easy editing
-# if [ -d "/var/www" ]; then
-# 	sudo chown -R "$USER":"$USER" /var/www
-# 	sudo chmod -R 755 /var/www
-# else
-# 	sudo mkdir -p /var/www
-# 	sudo chown -R "$USER":"$USER" /var/www
-# 	sudo chmod -R 755 /var/www
-# fi
+# Give the user ownership to website files for easy editing
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+fi
 
-# # create directories if not present
-# for dir in /var/www/{html,error}; do
-# 	if ! [ -d "$dir" ]; then
-# 		mkdir -p "$dir"
-# 	fi
-# done
-
-
+# create directories if not present
+for dir in /var/www/{html,error}; do
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
+done
 
 
-# # creating new index
-# echo "Hello World!" > /var/www/html/index.html
 
-# # create new error page
-# echo "Ceci n'est pas une page" > /var/www/html/error_404.html
 
-# # backup default server config file
-# sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
+# creating new index
+echo "Hello World!" > /var/www/html/index.html
 
-# # Add custom response header to know the server name for debugging
-# # Add to the nginx configuration file a error page 404
+# create new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
+
+# backup default server config file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
+
+# Add custom response header to know the server name for debugging
+# Add to the nginx configuration file a error page 404
 
 # server_config=\
 # "server {
-# 		listen 80 default_server;
+		#listen 80 default_server;
 # 		listen [::]:80 default_server;
 # 		root /var/www/html;
 # 		index index.html index.htm index.nginx-debian.html
@@ -81,14 +81,14 @@
 # 		}
 # }"
 
-# #shellcheck disable=SC2154
+#shellcheck disable=SC2154
 # echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
 
-# if [ "$(pgrep -c nginx)" -le 0 ]; then
-# 	sudo service nginx start
-# else
-# 	sudo service nginx restart
-# fi
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
+else
+	sudo service nginx restart
+fi
 
 
 
